export const mentors = [
    {
      name: "Каныбеков М ",
      profession: "Frontend",
      experience: "4 года",
      teacher: "Web-программирование (React)",
      topics: [
        "Основы HTML и CSS",
        "JavaScript для Frontend",
        "React и его экосистема",
        "Адаптивный дизайн",
        "Оптимизация производительности",
      ],
    },
    {
      name: "Каримов Э",
      profession: "Backend",
      experience: "3 года",
      teacher: "Проектирование и реализация серверной архитектуры (Django)",
      topics: [
        "Основы работы с Django",
        "RESTful API",
        "Работа с базами данных",
        "Аутентификация и авторизация",
        "Тестирование приложений",
      ],
    },
    {
      name: "Конурбаев А",
      profession: "UI/UX",
      experience: "2 года",
      teacher: "Типографика",
      topics: [
        "Основы UX-дизайна",
        "Типографика в веб-дизайне",
        "Прототипирование",
        "Исследование пользователей",
        "Создание пользовательских интерфейсов",
      ],
    },
    {
      name: "Кадырмышев А",
      profession: "Backend",
      experience: "3 года",
      teacher: "Программирование интерфейса сервера (PHP)",
      topics: [
        "PHP и MySQL",
        "MVC-паттерн",
        "Разработка RESTful API",
        "Интеграция с внешними сервисами",
        "Безопасность приложений",
      ],
    },
    {
      name: "Асанов К",
      profession: "Backend",
      experience: "4 года",
      teacher: "Разработка автоматизированных систем (Python)",
      topics: [
        "Основы Python для веб-разработки",
        "Flask и Django",
        "Работа с REST API",
        "Создание тестов на Python",
        "Разработка приложений с использованием Docker",
      ],
    },
    {
      name: "Петров Д",
      profession: "Frontend",
      experience: "1 год",
      teacher: "Web-программирование (Redux)",
      topics: [
        "Введение в React и Redux",
        "Управление состоянием приложения",
        "Асинхронные запросы с Redux",
        "Создание компонентов",
        "Тестирование компонентов",
      ],
    },
  ];